# Generated by Django 6.1.1 on 2026-09-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('available', 'موجود'), ('borrowed', 'امانت رفته')], default='available', max_length=10)),
            ],
        ),
    ]
